config/routes.rb
Rails.application.routes.draw do
  resources :club_students
  resources :exam_results
  resources :clubs
  resources :subjects
  devise_for :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students
  root to: 'students#index'
end

app/models/club.rb
class Club < ApplicationRecord
    
    has_many :clubs_students
    has_many :studetns, through: :club_students

    validates :name, presence: true
    validates :name, exclusion: { in: %w(部 サークル) }
    validates :name, length:{minimum:2}
    validates :name, length:{maximum:255}
    

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :authenticate_student!
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name)
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_form.html.erb
<%= form_with(model: club, local: true) do |form| %>
  <% if club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name ,'部活名'%>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "更新"%>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>編集ページ</h1>

<%= render 'form', club: @club %>

<%= link_to '表示', @club %> |
<%= link_to '戻る', clubs_path %>

app/views/clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>部活一覧</h1>

<table class= "table table-hover table-dark">
  <thead class="thead-light">
    <tr>
      <th>部活名</th>
      <th colspan="3"><%= link_to '部活追加', new_club_path, class:"btn btn-sm btn-block btn-outline-success" %></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.name %></td>
        <td><%= link_to '表示', club , class:"btn btn-outline-primary"%></td>
        <td><%= link_to '編集', edit_club_path(club) , class:"btn btn-outline-info"%></td>
        <td><%= link_to '削除', club, method: :delete, data: { confirm: 'よろしいですか？' } , class:"btn btn-outline-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規追加', new_club_path %>

app/views/clubs/new.html.erb
<h1>追加ページ</h1>

<%= render 'form', club: @club %>

<%= link_to '戻る', clubs_path %>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>部活:</strong>
  <%= @club.name %>
</p>

<%= link_to '編集', edit_club_path(@club) %> |
<%= link_to '戻る', clubs_path %>