config/routes.rb
Rails.application.routes.draw do
  resources :club_students
  resources :exam_results
  resources :clubs
  resources :subjects
  devise_for :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students
  root to: 'students#index'
end

app/models/student.rb
class Student < ApplicationRecord
  paginates_per 50
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :exam_results
  has_many :subjects, through: :exam_results
  has_many :club_students
  has_many :clubs, through: :club_students

  enum gender: { male: 0, female: 1 }
  enum age: { teen: 0, twenties: 1, thirties: 2 }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :authenticate_student!
    before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    #@students = Student.all.page params[:page]
    if current_student.admin?
      @students = Student.page params[:page]
    else
      @student = current_student
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @students = Student.joins(:subjects)
                       .select('students.name, students.email, students.age, students.gender, students.opinion, subjects.id as subject_id')
                       .select('exam_results.name as exam_result_name, subjects.name as subject_name, exam_results.score')
                       .select('CAST((exam_results.score / subjects.max_score) * 100 as int) as ratio')
                       .where(id: params[:id])
                       .order(id: :asc)

    avg_result = Student.joins(:subjects)
                        .select('subjects.id as subject_id')
                        .select('CAST(AVG(exam_results.score) as int) as avg_score')        
                        .select('MAX(exam_results.score) as max_score')
                        .select('MIN(exam_results.score) as min_score')
                        .group('subjects.id')
                        .order('subjects.id')
    @score_hash = {}
    avg_result.each do |avg_res|
      h = Hash.new
      h[:avg_score] = avg_res.avg_score
      h[:max_score] = avg_res.max_score
      h[:min_score] = avg_res.min_score                                                                                                                                     
      @score_hash[avg_res.subject_id] = h
    end
  end


  # GET /students/new
  def new
    @student = Student.new
  end
  
  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: '生徒情報が追加されました' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @student.update(student_params)
        #format.html { redirect_to :action => 'index', notice: 'Student was successfully updated.' }                                                               
        format.html { redirect_to action: :index, notice: '生徒情報が更新されました' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: '生徒情報は削除されました' }
      format.json { head :no_content }
    end
  end

  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :email, :gender, :age, :opinion)
    end
end

app/helpers/student_helper.rb
module StudentHelper
    def display_name(value)
        if value == 'male'
          '男性'
        elsif value == 'female'
          '女性'
        else
          '不明'
        end
      end
    
      def display_age(value)
        case value
        when 'teenage'
          '10代'
        when 'twenties'
          '20代'
        when 'thirties'
          '30代'
        else
          '不明'
        end
      end
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name ,'氏名'%>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email ,'メールアドレス'%>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :gender ,'性別'%>
    <%= form.radio_button :gender, 'male' %>男性
    <%= form.radio_button :gender, 'female' %>女性
  </div>

  <div class="field">
    <%= form.label :age ,'年齢'%>
    <%= form.radio_button :age, 'teen' %>10代
    <%= form.radio_button :age, 'twenties' %>20代
    <%= form.radio_button :age, 'thirties' %>30代
  </div>

  <div class="field">
    <%= form.label :opinion ,'その他'%>
    <%= form.text_area :opinion %>
  </div>

  <div class="actions">
    <%= form.submit "更新"%>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>生徒情報</h1>

<%= render 'form', student: @student %>

<%= link_to '表示', @student %> |
<%= link_to '戻る', students_path %>

app/views/students/index.html.erb
<div class="page-header">
<p id="notice"><%= notice %></p>

<h1>生徒データ一覧</h1>

<table class= "table table-hover table-dark">
  <thead class="thead-light">
    <tr>
      <th>pass:</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>性別</th>
      <th>年齢</th>
      <th>その他</th>
      <th colspan="5"><%= link_to '生徒追加', new_student_path , class:"btn btn-sm btn-block btn-outline-success"%></th>
    </tr>
  </thead>

  <tbody>
    <% if current_student.admin? %> 
      <% @students.each do |student| %>
        <tr>
          <td><%= student.password %></td>
          <td><%= student.name %></td>
          <td><%= student.email %></td>
          <td><%= display_name student.gender %></td>
          <td><%= display_age student.age %></td>
          <td><%= student.opinion %></td>
          <td><%= link_to '表示', student, class:"btn btn-outline-primary" %></td>
          <td><%= link_to '編集', edit_student_path(student) , class:"btn btn-outline-info" %></td>
          <td><%= link_to '削除', student, method: :delete, data: { confirm: 'よろしいですか？' } , class:"btn btn-outline-danger" %></td>
          <td><%= link_to '試験結果追加', new_exam_result_path(student_id: student.id), class:"btn btn-outline-warning" %></td>
          <td><%= link_to '所属部活追加', new_club_student_path(student_id: student.id), class:"btn btn-outline-warning" %></td>
        </tr>
     <% end %>
    <% else %>
      <tr>
        <td><%= @student.name %></td>
        <td><%= @student.email %></td>
        <td><%= display_name @student.gender %></td>
        <td><%= display_age @student.age %></td>
        <td><%= @student.opinion %></td>
        <td><%= link_to '表示', @student, class:"btn btn-outline-primary" %></td>
        <td><%= link_to '編集', edit_student_path(@student) , class:"btn btn-outline-info"  %></td>
        <td><%= link_to '削除', @student, method: :delete, data: { confirm: 'よろしいですか？' } , class:"btn btn-outline-danger" %></td>
        <td><%= link_to '試験結果追加', new_exam_result_path(student_id: @student.id), class:"btn btn-outline-warning" %></td>
        <td><%= link_to '所属部活追加', new_club_student_path(student_id: @student.id), class:"btn btn-outline-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_student.admin? %>
  <%= link_to '生徒追加', new_student_path , class:"btn btn-outline-success"%>
  <%= paginate @students %>
<% end %>

app/views/students/new.html.erb
<h1>生徒追加</h1>

<%= render 'form', student: @student %>

<%= link_to '戻る', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>氏名:</strong>
  <%= @student.name %>
</p>
<p>
<strong>pass:</strong>
<%= @student.password %>
</p>

<p>
  <strong>メールアドレス:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>性別:</strong>
  <%= @student.gender %>
</p>

<p>
  <strong>年齢:</strong>
  <%= @student.age %>
</p>

<p>
  <strong>その他:</strong>
  <%= @student.opinion %>
</p>

<p>
  <strong>試験結果:</strong>
</P>

<table border="1">
  <tr>
    <th>科目名</th>
    <th>点数</th>
    <th>平均</th>
    <th>最高</th>
    <th>最小</th>
  </tr>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.subject_name %></td>
      <td><%= student.score %></td>
      <td><%= @score_hash[student.subject_id][:avg_score] %></td>
      <td><%= @score_hash[student.subject_id][:max_score] %></td>
      <td><%= @score_hash[student.subject_id][:min_score] %></td>
    </tr>              
  <% end %>
</table>



<%= link_to '編集', edit_student_path(@student) %>
<%= link_to '戻る', students_path %>