config/routes.rb
Rails.application.routes.draw do
  resources :club_students
  resources :exam_results
  resources :clubs
  resources :subjects
  devise_for :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students
  root to: 'students#index'
end

app/models/club_student.rb
class ClubStudent < ApplicationRecord
  paginates_per 50
  belongs_to :student
  belongs_to :club
end

app/controllers/club_students_controller.rb
class ClubStudentsController < ApplicationController
  before_action :authenticate_student!
  before_action :set_club_student, only: [:show, :edit, :update, :destroy]
  before_action :set_students_clubs, only: [:new, :edit]

  # GET /club_students
  # GET /club_students.json
  def index
    @club_students = ClubStudent.all
  end

  # GET /club_students/1
  # GET /club_students/1.json
  def show
  end

  # GET /club_students/new
  #def new
   # @club_student = ClubStudent.new
  #end

   # GET /club_students/new
   def new
    if params[:student_id]
      @student = Student.find(params[:student_id])
      @selected_student = [@student.name, @student.id]
    end
    @club_student = ClubStudent.new
  end
  
  #club_studentsのnewページをセレクトボックスにする
  def set_students_clubs
    @students = Student.all.pluck(:name, :id)
    @clubs = Club.all.pluck(:name, :id)
  end
  # GET /club_students/1/edit
  def edit
  end

  # POST /club_students
  # POST /club_students.json
  def create
    @club_student = ClubStudent.new(club_student_params)

    respond_to do |format|
      if @club_student.save
        format.html { redirect_to @club_student, notice: 'Club student was successfully created.' }
        format.json { render :show, status: :created, location: @club_student }
      else
        format.html { render :new }
        format.json { render json: @club_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /club_students/1
  # PATCH/PUT /club_students/1.json
  def update
    respond_to do |format|
      if @club_student.update(club_student_params)
        format.html { redirect_to @club_student, notice: 'Club student was successfully updated.' }
        format.json { render :show, status: :ok, location: @club_student }
      else
        format.html { render :edit }
        format.json { render json: @club_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /club_students/1
  # DELETE /club_students/1.json
  def destroy
    @club_student.destroy
    respond_to do |format|
      format.html { redirect_to club_students_url, notice: 'Club student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club_student
      @club_student = ClubStudent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_student_params
      params.require(:club_student).permit(:student, :club_id)
    end
end

app/helpers/club_students_helper.rb
module ClubStudentsHelper
end

app/views/club_students/_form.html.erb
<%= form_with(model: club_student, local: true) do |form| %>
  <% if club_student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(club_student.errors.count, "error") %> prohibited this club_student from being saved:</h2>

      <ul>
      <% club_student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id ,'生徒'%>
    <%= form.select :student_id, options_for_select(@students, @selected_student) %>
  </div>

  <div class="field">
    <%= form.label :club_id ,'部活'%>
    <%= form.select :club_id, @clubs %>
  </div>
<!--
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
-->
  <div class="actions">
    <%= form.submit "更新"%>
  </div>
<% end %>

app/views/club_students/edit.html.erb
<h1>加入情報編集</h1>

<%= render 'form', club_student: @club_student %>

<%= link_to '編集', @club_student %> |
<%= link_to '戻る', club_students_path %>

app/views/club_students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>部活所属状況</h1>

<table class= "table table-hover table-dark" >
  <thead class="thead-light">
    <tr>
      <th>生徒</th>
      <th>部活</th>
      <th colspan="3"><%= link_to '所属情報追加', new_club_student_path, class:"btn btn-sm btn-block btn-outline-success"%></th>
    </tr>
  </thead>

  <tbody>
    <% @club_students.each do |club_student| %>
      <tr>
        <td><%= club_student.student.name %></td>
        <td><%= club_student.club.name %></td>
        <td><%= link_to '表示', club_student , class:"btn btn-outline-primary"%></td>
        <td><%= link_to '編集', edit_club_student_path(club_student) , class:"btn btn-outline-info"%></td>
        <td><%= link_to '削除', club_student, method: :delete, data: { confirm: 'よろしいですか？' } , class:"btn btn-outline-danger"%></td>
     </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '所属情報追加', new_club_student_path %>

app/views/club_students/new.html.erb
<h1>加入情報追加</h1>

<%= render 'form', club_student: @club_student %>

<%= link_to '戻る', club_students_path %>

app/views/club_students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>生徒:</strong>
  <%= @club_student.student %>
</p>

<p>
  <strong>部活:</strong>
  <%= @club_student.club %>
</p>

<!--
<p>
  <strong>Name:</strong>
  <%= @club_student.name %>
</p>
-->

<%= link_to '編集', edit_club_student_path(@club_student) %> |
<%= link_to '戻る', club_students_path %>