config/routes.rb
Rails.application.routes.draw do
  resources :club_students
  resources :exam_results
  resources :clubs
  resources :subjects
  devise_for :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students
  root to: 'students#index'
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :exam_results
    has_many :studetns, through: :exam_results

    validates :name, presence: true
    validates :name, length: { minimum: 2 }
    validates :name, length: { maximum: 255 }

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :authenticate_student!
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :max_score)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name ,'教科'%>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :max_score ,'配点'%>
    <%= form.number_field :max_score %>
  </div>

  <div class="actions">
    <%= form.submit "更新"%>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>編集ページ</h1>

<%= render 'form', subject: @subject %>

<%= link_to '表示', @subject %> |
<%= link_to '戻る', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>教科一覧</h1>

<table class= "table table-hover table-dark">
  <thead class="thead-light">
    <tr>
      <th>教科</th>
      <th>配点</th>
      <th colspan="3"><%= link_to '教科追加', new_subject_path, class:"btn btn-sm btn-block btn-outline-success" %></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.max_score %> 点</td>
        <td><%= link_to '表示', subject , class:"btn btn-outline-primary"%></td>
        <td><%= link_to '編集', edit_subject_path(subject) , class:"btn btn-outline-info"%></td>
        <td><%= link_to '削除', subject, method: :delete, data: { confirm: 'よろしいですか？' } , class:"btn btn-outline-danger"%></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規追加', new_subject_path %>

app/views/subjects/new.html.erb
<h1>追加ページ</h1>

<%= render 'form', subject: @subject %>

<%= link_to '戻る', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>教科:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>配点:</strong>
  <%= @subject.max_score %> 点
</p>

<%= link_to '編集', edit_subject_path(@subject) %> |
<%= link_to '戻る', subjects_path %>